import { CheckCircle2, FileCheck, AlertTriangle } from 'lucide-react';
import { Card } from '../ui/card';
import { Button } from '../ui/button';
export function ReadinessCard({ documents = [], report, onFix, processing = false }) {
  const uploaded = documents.filter(d => d.storedName).length;
  const percentage = report?.readiness.score || 0;
  const ready = report?.readiness.ready === true;
  const issues = report?.issues.filter(i => i.severity !== 'info') || [];
  const circumference = 2 * Math.PI * 54;
  return <Card className="readiness-card"><div className="readiness-top"><div className="radial-progress-wrapper" role="meter" aria-label="Pre-submission validation readiness" aria-valuenow={percentage} aria-valuemin={0} aria-valuemax={100}><svg aria-hidden="true" className="radial-svg" width="130" height="130" viewBox="0 0 130 130"><circle className="radial-bg" cx="65" cy="65" r="54" strokeWidth="10"/><circle className={`radial-fill ${ready ? 'radial-complete' : ''}`} cx="65" cy="65" r="54" strokeWidth="10" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - percentage / 100)} strokeLinecap="round"/></svg><div className="radial-text"><span className="radial-value">{percentage}%</span></div></div><div className="readiness-titles"><h3>Application Readiness</h3><p className="readiness-label">{processing ? 'Checking your application...' : report?.readiness.label || 'Not yet validated'}</p><p className="readiness-sub">Pre-submission checks, not a prediction of government approval.</p><div className="readiness-doc-count"><FileCheck size={14}/><span><strong>{uploaded} / {documents.length}</strong> documents uploaded</span></div></div></div><div className="readiness-formula"><span>Completeness <strong>40%</strong></span><span>Document checks <strong>40%</strong></span><span>Name consistency <strong>20%</strong></span></div>{issues.length > 0 && <div className="readiness-issues"><strong><AlertTriangle size={17}/>{issues.length} Issues Found</strong><p>Review the flagged documents before submitting.</p><Button variant="outline" onClick={onFix} disabled={processing}>Fix Issues</Button></div>}{ready && <p className="readiness-passed"><CheckCircle2 size={17}/>Pre-validation Passed</p>}</Card>;
}
