import { Link } from 'react-router-dom';
import { Plus, ArrowRight, Factory, MapPin, Info } from 'lucide-react';
import { PageHeader } from '../../components/layout/PageHeader';
import { MetricCard } from '../../components/shared/MetricCard';
import { StatusBadge } from '../../components/shared/StatusBadge';
import { Card } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { dashboardMetrics, entrepreneurApplications } from '../../data/demoApplications';
export function EntrepreneurDashboard() { return <><PageHeader eyebrow="Welcome back, Katyayani" title="Let's move your business forward!" description="Your applications, with a little more clarity." action={<Button asChild><Link to="/entrepreneur/applications/new"><Plus/>Start New Application</Link></Button>}/><div className="metrics-grid">{dashboardMetrics.entrepreneur.map(metric => <MetricCard key={metric.label} {...metric}/>)}</div><section className="applications-section"><div className="section-heading"><h2>My Applications <span className="count">3</span></h2><Link to="/entrepreneur/applications">View all <ArrowRight size={15}/></Link></div><div className="application-list">{entrepreneurApplications.map(application => <Card key={application.id} className="application-card"><span className={`application-icon tone-${application.tone}`}><Factory size={24}/></span><div className="application-info"><h3>{application.name}</h3><p><MapPin size={13}/>{application.location}</p><small>{application.id} · {application.department}</small></div><StatusBadge tone={application.tone}>{application.status}</StatusBadge><span className="sample-label">Demo record</span></Card>)}</div></section><div className="workspace-note"><Info size={19}/><p><strong>A foundation for better applications.</strong> This preview uses sample records. Application creation, validation and tracking will arrive in later phases.</p></div><Card className="assistance-card"><div><h2>A better start is a clearer start.</h2><p>Explore the future home of regulatory guidance for your business.</p></div><Button asChild variant="outline"><Link to="/entrepreneur/assistant">Regulatory Assistant <ArrowRight/></Link></Button></Card></>; }
